services:
  - type: web
    name: flask-tensorflow-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: API.py
      - key: FLASK_ENV
        value: production
