services:
  - type: web
    name: flask-tensorflow-app
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python API.py
    envVars:
      - key: FLASK_ENV
        value: production
